    DROP TABLE IF EXISTS stats;

    CREATE TABLE IF NOT EXISTS stats (
        ID         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        App	       VARCHAR(255) NOT NULL,
        URI        VARCHAR(255) NOT NULL,
        IP	       VARCHAR(255) NOT NULL,
        time_stamp TIMESTAMP NOT NULL,
        CONSTRAINT pk_stats PRIMARY KEY (ID)
        );